name: Run tests to validate the code
on: [pull_request]

permissions:
  contents: read # for checkout

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Install dependencies
        run: npm clean-install
      - name: Run unit tests
        run: npx mocha --require esm 'tests/unit/**/*.test.js'